#!/bin/bash

#
# Small script to setup an SSH honey pot
#
# @author Andrew Smith <me@andrewmichaelsmith.com>
# @author Pieter Maene <pieter@maene.eu>
#

generateRestoreScript() {
cat <<EOF
#!/bin/sh

#
# Restore IPTables rules
# @author Pieter Maene <pieter@maene.eu>
#

iptables-restore < /etc/iptables.rules
exit 0
EOF
}

if [ "$EUID" != "0" ]; then
    sudo "$0" $@
    exit $?
fi

# Aptitude
aptitude update

# p0f
aptitude install -y p0f
mkdir /var/p0f/

#
# Kippo
aptitude install -y subversion python-dev openssl python-openssl python-pyasn1 python-twisted iptables

mkdir /opt/kippo/
svn checkout http://kippo.googlecode.com/svn/trunk/ /opt/kippo/

wget https://raw.github.com/Pmaene/HoneyPot/master/config/kippo.cfg -O /opt/kippo/kippo.cfg

useradd -r -s /bin/false kippo

mkdir -p /var/kippo/dl
mkdir -p /var/kippo/log/tty
mkdir -p /var/run/kippo

rm -rf /opt/kippo/dl
rm -rf /opt/kippo/log

chown -R kippo:kippo /opt/kippo/
chown -R kippo:kippo /var/kippo/
chown -R kippo:kippo /var/run/kippo/

# Change SSH port
sed -i 's/Port 22/Port 10001/g' /etc/ssh/sshd_config
service ssh reload

# Flushing existing IPTables configuration
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X

# Preroute all traffic on port 22 to 222
iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 2222

# Persist iptables config
iptables-save > /etc/iptables.rules

generateRestoreScript > /etc/network/if-up.d/iptables
chmod +x /etc/network/if-up.d/iptables

# Retrieve init scripts
wget https://raw.github.com/Pmaene/HoneyPot/master/init/p0f -O /etc/init.d/p0f
wget https://raw.github.com/Pmaene/HoneyPot/master/init/kippo -O /etc/init.d/kippo

# Install system services
chmod +x /etc/init.d/p0f
chmod +x /etc/init.d/kippo

update-rc.d p0f defaults
update-rc.d kippo defaults

# Start the honeypot software
service p0f start
service kippo start
